version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./django.conf:/etc/nginx/conf.d/default.conf
      - ./production_data/static:/static
  django:
    build: .
    command: bash -c "sleep 10; python manage.py collectstatic --noinput; python manage.py migrate & daphne -b 0.0.0.0 -p 8000 cookbook.asgi:application"
    volumes:
      - ./production_data/sqlite:/data
      - ./production_data/static:/static
    environment:
      - "PRODUCTION=True"
  db:
    image: postgres
    restart: always                                                                                                                                                                                                                         
    environment:                                                                                                                                                                                                                            
      POSTGRES_PASSWORD: cookbook                                                                                                                                                                                                           
      POSTGRES_USER: cookbook                                                                                                                                                                                                               
      POSTGRES_DB: cookbook                                                                                                                                                                                                                 
    volumes:                                                                                                                                                                                                                                
      - ./production_data/pg:/var/lib/postgresql/data
