version: "3"

services:
  web:
    build: .
    command: bash -c "sleep 10; python manage.py migrate & daphne -b 0.0.0.0 -p 8000 cookbook.asgi:application"
    volumes:
      - ./production_data/sqlite:/data
    ports:
      - 80:8000
    environment:
      - "PRODUCTION=True"
  db:
    image: postgres
    restart: always                                                                                                                                                                                                                         
    environment:                                                                                                                                                                                                                            
      POSTGRES_PASSWORD: cookbook                                                                                                                                                                                                           
      POSTGRES_USER: cookbook                                                                                                                                                                                                               
      POSTGRES_DB: cookbook                                                                                                                                                                                                                 
    volumes:                                                                                                                                                                                                                                
      - ./production_data/pg:/var/lib/postgresql/data
